Issue #105 - PMDise Catalog Metadata
GSS-Cogs/csvcubed pull request #248
Opened 2021-11-23 15:07 UTC by robons

Added a new CLI command which strips out the DCAT catalog metadata out of the `file.csv-metadata.json` file and drops it into a `file.csv-metadata.json.nq` N-Quads file.

```
$ pmdutils dcat pmdify --help
Usage: pmdutils dcat pmdify [OPTIONS] CSVW_METADATA_FILE BASE_URI
                            DATA_GRAPH_URI CATALOG_METADATA_GRAPH_URI

  Given a local CSV-W metadata file, re-work the DCATv2 metadata such that it
  ends up in the format required for PMD
```

2021-11-25 14:45 UTC, canwaf commented
I stripping out the catalog data from a unified file necessary for PMD to process it? @robons

2021-11-25 14:46 UTC, robons commented
> I stripping out the catalog data from a unified file necessary for PMD to process it? @robons

Since we're separating it out into a separate graph/file we don't want to duplicate the information we're uploading.

2021-11-25 15:25 UTC, canwaf requested changes
The code looks fine, and I can assume it does what it says on the tin (behave says so); however you need to address the following:
- [ ] pyrite fails (6 errors)
- [ ] unit test: test_extracting_metadata(): fails (assertion on comment)

The cli structure is getting unwieldly where there are keywords after keywords after keywords. That said the helpfile should mention that input isn't exclusively metadata, and that the metadata gets removed from the source and output is multiple files.

2021-11-25 15:25 UTC, canwaf commented on csvcubed-pmd/tests/unit/dcatcli/test_pmdify.py
> +    assert existing_dcat_dataset.comment == "some comment goes here"
Unit test fails here.

2021-11-25 16:04 UTC, robons commented on csvcubed-pmd/tests/unit/dcatcli/test_pmdify.py
> +    assert existing_dcat_dataset.comment == "some comment goes here"
fixed

2021-11-26 09:22 UTC, canwaf approved these changes
Thanks for fixing it all.

2021-11-26 09:25 UTC, merged