Issue 508/defining measures bug
GSS-Cogs/csvcubed pull request #509
Opened 2022-05-31 14:31 UTC by mikeAdamss

bug fix for: https://app.zenhub.com/workspaces/features-squad-61b72275ac896c0010a1b00b/issues/gss-cogs/csvcubed/508

2022-06-07 13:36 UTC, mikeAdamss commented on csvcubed/csvcubed/models/cube/qb/validationerrors.py
> +class EmptyQbMultiMeasureDimensionError(SpecificValidationError):
reading that file is the worst thing that's happened to me today 😬

2022-06-10 10:56 UTC, robons commented on src/csvcubed/models/cube/qb/validationerrors.py
> +        return 'http://purl.org/csv-cubed/err/empty-multi-meas-dimension'
The documentation pages corresponding to these URIs need to be part of this PR too.

This is the location where they should be created:

https://github.com/GSS-Cogs/csvcubed/tree/main/external-docs/docs/guides/errors/build-command-errors

Once they've been set up, we can create the PURL url mappings.

2022-06-10 10:58 UTC, robons requested changes
Looks good, but make sure you add the help documentation in for those new errors you're put in.

2022-06-14 11:18 UTC, robons approved these changes
Don't forget those PURL URLs are made before the next release.

2022-06-14 11:24 UTC, merged