518 codelist same as bug
GSS-Cogs/csvcubed pull request #616
Opened 2022-10-05 08:27 UTC by GDonRanasinghe

Fixed the output csv not having the same as uri column when the concepts defined elsewhere are used.

2022-10-05 09:04 UTC, robons commented on tests/unit/models/test_code_list_config.py
> +        assert "Original Concept URI" in output_df.columns
Can you make sure the URIs you're expecting get serialised?

2022-10-05 09:07 UTC, robons approved these changes
Approved on the condition that you test that the same as URIs defined in the JSON file are definitely in the data frame/CSV.

2022-10-05 13:01 UTC, canwaf requested changes
This change has regressed the functionality for the `from_template: year` configuration option.

Additionally, you have put live data in your tests. Please synthesise more narrow test cases for unit tests.

I need to have the from_template functionality working. Let's talk about how the serialisation has changed and how we can improve our test coverage to prevent future regression from getting to this point.

2022-10-06 15:19 UTC, canwaf approved these changes
Thank you @CharlesRendle for making generic tests for this; and only testing one instance (since we only need to test things once).

2022-10-06 15:24 UTC, merged