652 inspect api cached properties
GSS-Cogs/csvcubed pull request #693
Opened 2023-01-18 11:27 UTC by CharlesRendle

PR addressing issue #652

TODO: write this description

2023-01-18 15:25 UTC, CharlesRendle commented on tests/unit/cli/inspect/test_inspectdatasetmanager.py
> +        csvw_rdf_manager.rdf_graph, csvw_metadata_json_path
Flag.
Think this was our changes a few days ago but flagged just to be sure

2023-01-18 15:26 UTC, CharlesRendle commented on tests/profiling/csvcubed_inspect_process.py
> +from csvcubed.cli.build import build
Flag.

2023-01-18 15:27 UTC, CharlesRendle commented on tests/profiling/csvcubed_build_process.py
> +from tempfile import TemporaryDirectory
Flag.
Presumably moved during first use of new commit hook

2023-01-19 11:00 UTC, CharlesRendle commented on tests/unit/utils/sparqlhandler/test_sparqlquerymanager.py
> +    select_units,
Removed.

2023-01-19 11:08 UTC, CharlesRendle commented on tests/profiling/csvcubed_inspect_process.py
> +from csvcubed.cli.build import build
Keeping as isort should rearrange in this fashion.

2023-01-19 11:08 UTC, CharlesRendle commented on tests/profiling/csvcubed_build_process.py
> +from tempfile import TemporaryDirectory
Keeping as isort should rearrange in this fashion.

2023-01-19 15:35 UTC, CharlesRendle commented on tests/unit/cli/inspect/test_inspectdatasetmanager.py
> +        csvw_rdf_manager.rdf_graph, csvw_metadata_json_path
Resolved without change.

2023-01-19 16:30 UTC, robons requested changes
Looks really good to me. I think there are a few changes we can make to tidy it up a little bit more before merging it in.

2023-01-20 12:58 UTC, CharlesRendle commented on src/csvcubed/cli/inspect/inspect.py
> +    csvw_state = CsvWState(
`CsvWState` now passed into `_generate_printables()` function. Also now using this to get the `csvw_type` in `_generate_printables()`

2023-01-20 12:59 UTC, CharlesRendle commented on src/csvcubed/cli/inspect/metadataprinter.py
> +            csvw_state.csvw_json_path,
Removed `csvw_json_path` but have kept qube_components because we need this defined for `dsd_info_printable`

2023-01-20 12:59 UTC, CharlesRendle commented on src/csvcubed/models/sparqlresults.py
> +    graph_uri: str
Comment added

2023-01-20 12:59 UTC, CharlesRendle commented on src/csvcubed/utils/sparql_handler/code_list_state.py
> +from functools import cached_property
imports removed

2023-01-20 12:59 UTC, CharlesRendle commented on src/csvcubed/utils/sparql_handler/csvw_state.py
> +    primary_graph_uri: str
__post_init__ added

2023-01-20 13:00 UTC, CharlesRendle commented on src/csvcubed/utils/sparql_handler/data_cube_state.py
>  import rdflib
Import removed

2023-01-20 15:55 UTC, robons approved these changes
**Make sure you sort out the comment I've left about the primary_graph_uri dataclass property definition before merging**

2023-01-20 15:55 UTC, robons commented on src/csvcubed/cli/inspect/metadataprinter.py
> +    state: Union[DataCubeState, CodeListState]
I'm tempted to rename these things `CsvWInspector`, `DataCubeInspector` and `CodeListInspector`. You two got any thoughts on that?

2023-01-20 15:55 UTC, robons commented on src/csvcubed/utils/sparql_handler/csvw_state.py
> +        self.primary_graph_uri = path_to_file_uri_for_rdflib(self.csvw_json_path)
Can you make sure to declare this field in the above list? 

```
primary_graph_uri: str = field(init=False)
```

should suffice to make it clear it's not to be part of the `__init__` constructor.

2023-01-23 14:02 UTC, merged