#777 worked example #3 for Inspect API docs
GSS-Cogs/csvcubed pull request #833
Opened 2023-06-21 15:26 UTC by NickPapONS

2023-06-22 11:32 UTC, nimshi89 requested changes

2023-06-22 11:32 UTC, nimshi89 commented on external-docs/docs/guides/inspect-api/index.md
> +Text here
I am not sure about this

2023-06-22 11:32 UTC, nimshi89 commented on external-docs/docs/guides/inspect-api/index.md
> +Text here
also this one

2023-06-23 10:00 UTC, SarahJohnsonONS commented
Changed the placeholder text in index.md to "To follow"

2023-06-23 13:15 UTC, nimshi89 approved these changes
Seems great

2023-06-26 08:58 UTC, merged

2023-06-27 13:35 UTC, robons commented on external-docs/docs/guides/inspect-api/example3.md
> +>>> df, errors = data_cube_repository.get_dataframe(csv_url=csv_url, include_suppressed_cols=False, dereference_uris=False)
But it looks like the URIs have been dereferenced to their labels in this example?

2023-06-27 13:39 UTC, robons commented on external-docs/docs/guides/inspect-api/example3.md
> +![Correlation heatmap](../../images/heatmap.png)
This image seems to be missing.

2023-06-27 13:40 UTC, robons commented on external-docs/docs/guides/inspect-api/example3.md
> +![Correlation heatmap](../../images/heatmap.png)
So is the eigenvalues one.

2023-06-27 13:41 UTC, robons commented on external-docs/docs/guides/inspect-api/example3.md
> +>>> glm_formula = f"{value_col_title} ~ {dimension_col_title}"
Won't this only work if there's just one dimension? What happens when there is more than one dimension?

2023-06-27 13:42 UTC, robons commented on external-docs/docs/guides/inspect-api/example3.md
> +>>> summary = glm_model.summary()
Can we see the results with a little bit of interpretation? It'd be good to have some interpretation of the factor analysis too.

2023-06-27 13:43 UTC, robons commented
It looking really good to me but could do with a few bits of tidying up. Glad you got to the point of being able to run these analyses without having to hard-code configuration for each individual CSV-W.